# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Declare a dependency on the welcome-orb
  my-orb:
    executors:
      specialthingexecutor:
        docker:
          - image: coinbase/salus:2.4.1
    jobs:
      myjob:
        executor: specialthingexecutor
        working_directory: /home
        steps:
          - run: |
              echo " 
                config_version: 1

                active_scanners: all

                enforced_scanners:
                  - RepoNotEmpty
                  - Brakeman
                  - BundleAudit
                  - Gosec
                  - NPMAudit
                  - YarnAudit
                  - PatternSearch
                reports:
                  - uri: file://salus-report.json
                    format: json" | tee ./salus.yaml 
          - checkout:
              path: ./repo
          - run: 
              name: run scan
              command: |
                  /usr/local/bundle/bin/bundle exec ./bin/salus scan --config file://salus.yaml
          - run: pwd
          - run: ls -l
          - run: ls -l /home
          - run: ls -l bin
          - run: ls -l repo
          - store_artifacts:
              path: ./salus-report.json


# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  main:
    jobs:
      - my-orb/myjob

