# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  salustest: jsresearch/salustest@dev:first

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  main:
    jobs:
      - salustest/scan:
          active_scanners: 
            - Brakeman

