# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  salus: federacy/salus@dev:0.0.4

executors:
  salus_latest:
    docker:
      - image: coinbase/salus:2.4.1

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  main:
    jobs:
      - salus/scan:
          enforced_scanners: "none"
          #salus_executor: 
          #  name: "salus_latest"
            #name: salus_latest
#      - salustest/scan:
#          report_uri: "https://postb.in/G3onBUfO"
#      - salustest/scan:
#          active_scanners: "\n    - Brakeman"


















